name: Primeira Treta no Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout no Código Fonte
      uses: actions/checkout@v2

    - name: Criando Pasta para Deploy
      run: zip -r deploy.zip . -x '*.git*'

    - name: Logando no Sistema
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Buildando o Projeto
      run: docker build -t mafideju/docker-react-101 -f Dockerfile.dev .
    
    - name: Rodando o Build
      run: docker run -e CI=true mafideju/docker-react-101 npm test

    - name: Criando Imagem Docker
      run: docker build . --file Dockerfile --tag docker-react-101:$(date +%s)
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: docker-react-101
        environment_name: Dockerreact101-env
        existing_bucket_name: elasticbeanstalk-us-east-1-788553702873
        region: us-east-1
        version_label: 005
        deployment_package: deploy.zip

