name: Primeira Treta no Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build -t mafideju/docker-react-101 -f Dockerfile.dev .
    - run: docker run -e CI=true mafideju/docker-react-101 npm test

    - name: Criando Imagem Docker
      run: docker build . --file Dockerfile --tag docker-react-101:$(date +%s)
      

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}

        application_name: docker-react-101
        environment_name: Dockerreact101-env
        existing_bucket_name: eba-gmuhwxs9.us-east-1.elasticbeanstalk.com.
        region: us-east-1

        version_label: 001
        deployment_package: deploy.zip

